#!/bin/sh
set -e

# Host keys are the borg server's identity. Nodes record their fingerprint in
# known_hosts on first contact, so if the keys change the nodes refuse to
# connect with REMOTE HOST IDENTIFICATION HAS CHANGED and backups stop.
#
# Keys baked into the image are regenerated by every uncached rebuild, so they
# live on a named volume mounted here instead.
KEY_DIR=/etc/ssh/keys

mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR"

for type in ed25519 rsa ecdsa; do
    persisted="$KEY_DIR/ssh_host_${type}_key"
    baked="/etc/ssh/ssh_host_${type}_key"

    # Upgrading an existing installation: adopt the key already in the image so
    # the server keeps the identity nodes have on record.
    if [ ! -f "$persisted" ] && [ -f "$baked" ]; then
        cp "$baked" "$persisted"
        [ -f "$baked.pub" ] && cp "$baked.pub" "$persisted.pub"
        echo "Adopted the existing $type host key into $KEY_DIR"
        continue
    fi

    # Fresh installation: generate once, then reuse for the life of the volume.
    if [ ! -f "$persisted" ]; then
        ssh-keygen -q -t "$type" -N "" -f "$persisted"
        echo "Generated a new $type host key"
    fi
done

chmod 600 "$KEY_DIR"/ssh_host_*_key
chmod 644 "$KEY_DIR"/ssh_host_*_key.pub

echo "borg-server host key fingerprints:"
for pub in "$KEY_DIR"/ssh_host_*_key.pub; do
    ssh-keygen -lf "$pub"
done

mkdir -p /var/run/sshd
exec /usr/sbin/sshd -D -e
