"""add_kiosk_enrollment_fields_and_settings_ips

Revision ID: 090ff8ce55f0
Revises: 858739b62574
Create Date: 2026-06-24 13:16:09.863179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090ff8ce55f0'
down_revision: Union[str, None] = '858739b62574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiosks', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('kiosks', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('server_ips', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'server_ips')
    op.drop_column('kiosks', 'comment')
    op.drop_column('kiosks', 'phone')
    # ### end Alembic commands ###
