"""add_kiosk_iso_built_at

Revision ID: 1a81d84adb9f
Revises: 8b821f8f1bd0
Create Date: 2026-07-07 14:22:03.208616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a81d84adb9f'
down_revision: Union[str, None] = '8b821f8f1bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiosks', sa.Column('iso_built_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiosks', 'iso_built_at')
    # ### end Alembic commands ###
