"""add_ping_status_to_nodes

Revision ID: 236715e36c6e
Revises: 714a50d23bfd
Create Date: 2026-07-13 10:31:35.857023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236715e36c6e'
down_revision: Union[str, None] = '714a50d23bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('last_ping_status', sa.Boolean(), nullable=True))
    op.add_column('nodes', sa.Column('last_available_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'last_available_at')
    op.drop_column('nodes', 'last_ping_status')
    # ### end Alembic commands ###
