"""add partition layout to nodes

Revision ID: 52d93226efae
Revises: 944f46d13cfd
Create Date: 2026-05-25 12:25:30.081582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d93226efae'
down_revision: Union[str, None] = '944f46d13cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('partition_layout', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'partition_layout')
    # ### end Alembic commands ###
