"""add_bootstrap_credentials

Revision ID: 5cba392850b4
Revises: 3f2c850a3af3
Create Date: 2026-07-09 08:18:11.239124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cba392850b4'
down_revision: Union[str, None] = '3f2c850a3af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('bootstrap_credentials', sa.JSON(), nullable=True))
    op.add_column('settings', sa.Column('default_credentials_id', sa.String(), nullable=True))
    op.alter_column('settings', 'global_exclusions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'global_exclusions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('settings', 'default_credentials_id')
    op.drop_column('settings', 'bootstrap_credentials')
    # ### end Alembic commands ###
