"""add_timezone_to_backup_groups

Revision ID: 768e6389800a
Revises: da61ca2f70db
Create Date: 2026-06-14 19:04:41.688791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768e6389800a'
down_revision: Union[str, None] = 'da61ca2f70db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_groups', sa.Column('timezone', sa.String(), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backup_groups', 'timezone')
    # ### end Alembic commands ###
