"""add kiosk target ip and rebuild flag

Revision ID: 8b821f8f1bd0
Revises: a561a746277c
Create Date: 2026-07-07 08:23:54.628684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b821f8f1bd0'
down_revision: Union[str, None] = 'a561a746277c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiosks', sa.Column('target_ip', sa.String(), nullable=True))
    op.add_column('kiosks', sa.Column('rebuild_required', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiosks', 'rebuild_required')
    op.drop_column('kiosks', 'target_ip')
    # ### end Alembic commands ###
