"""add_kiosk_last_seen

Revision ID: a561a746277c
Revises: 68b32bc20456
Create Date: 2026-07-06 10:25:03.208616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a561a746277c'
down_revision: Union[str, None] = '68b32bc20456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiosks', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_kiosks_uuid'), table_name='kiosks')
    op.create_index(op.f('ix_kiosks_kiosk_id'), 'kiosks', ['kiosk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiosks_kiosk_id'), table_name='kiosks')
    op.create_index(op.f('ix_kiosks_uuid'), 'kiosks', ['kiosk_id'], unique=True)
    op.drop_column('kiosks', 'last_seen')
    # ### end Alembic commands ###
