"""add_kiosks_table

Revision ID: d3e2b98f0028
Revises: 7ca91198b689
Create Date: 2026-06-17 11:30:57.096634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e2b98f0028'
down_revision: Union[str, None] = '7ca91198b689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('ssh_pub_key', sa.Text(), nullable=True),
    sa.Column('auth_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_token')
    )
    op.create_index(op.f('ix_kiosks_id'), 'kiosks', ['id'], unique=False)
    op.create_index(op.f('ix_kiosks_key'), 'kiosks', ['key'], unique=True)
    op.create_index(op.f('ix_kiosks_uuid'), 'kiosks', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiosks_uuid'), table_name='kiosks')
    op.drop_index(op.f('ix_kiosks_key'), table_name='kiosks')
    op.drop_index(op.f('ix_kiosks_id'), table_name='kiosks')
    op.drop_table('kiosks')
    # ### end Alembic commands ###
