"""add backup groups and node details

Revision ID: da61ca2f70db
Revises: 96df8f3b4731
Create Date: 2026-06-14 15:31:03.634740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da61ca2f70db'
down_revision: Union[str, None] = '96df8f3b4731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('target_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('randomize_days', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_groups_id'), 'backup_groups', ['id'], unique=False)
    op.create_index(op.f('ix_backup_groups_name'), 'backup_groups', ['name'], unique=True)
    op.add_column('nodes', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('nodes', sa.Column('backup_paused', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('nodes', sa.Column('backup_today', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('nodes', sa.Column('missed_window', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('nodes', sa.Column('cpu_info', sa.String(), nullable=True))
    op.add_column('nodes', sa.Column('memory_info', sa.String(), nullable=True))
    op.add_column('nodes', sa.Column('edge_version', sa.String(), nullable=True))
    op.add_column('nodes', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'nodes', 'backup_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_column('nodes', 'notes')
    op.drop_column('nodes', 'edge_version')
    op.drop_column('nodes', 'memory_info')
    op.drop_column('nodes', 'cpu_info')
    op.drop_column('nodes', 'missed_window')
    op.drop_column('nodes', 'backup_today')
    op.drop_column('nodes', 'backup_paused')
    op.drop_column('nodes', 'group_id')
    op.drop_index(op.f('ix_backup_groups_name'), table_name='backup_groups')
    op.drop_index(op.f('ix_backup_groups_id'), table_name='backup_groups')
    op.drop_table('backup_groups')
    # ### end Alembic commands ###
