"""add max_kiosk_isos to settings

Revision ID: e4175f219b5b
Revises: 090ff8ce55f0
Create Date: 2026-06-24 16:27:27.660692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4175f219b5b'
down_revision: Union[str, None] = '090ff8ce55f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('max_kiosk_isos', sa.Integer(), nullable=False, server_default='5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'max_kiosk_isos')
    # ### end Alembic commands ###
