"""add_retention_policy_to_settings_and_groups

Revision ID: eb89a8231897
Revises: 768e6389800a
Create Date: 2026-06-14 20:05:29.893556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb89a8231897'
down_revision: Union[str, None] = '768e6389800a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_groups', sa.Column('override_retention', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('backup_groups', sa.Column('retention_policy', sa.JSON(), nullable=True))
    op.add_column('settings', sa.Column('retention_policy', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'retention_policy')
    op.drop_column('backup_groups', 'retention_policy')
    op.drop_column('backup_groups', 'override_retention')
    # ### end Alembic commands ###
