"""Add server_net_capacity_mbps

Revision ID: f8c08968db77
Revises: bb91ad4a73fe
Create Date: 2026-07-15 11:03:34.307477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c08968db77'
down_revision: Union[str, None] = 'bb91ad4a73fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('server_net_capacity_mbps', sa.Integer(), nullable=False, server_default='1000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'server_net_capacity_mbps')
    # ### end Alembic commands ###
